name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run tests
      run: npm test

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Important for semantic-release to detect commits

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Semantic Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ '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' }}