name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.0'

    - name: Install Dependencies
      run: npm install

    - name: ESLint Check
      run: npm run lint

    - name: Prettier Check
      run: npm run format-check

    - name: Run tests
      run: npm test

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.0'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Semantic Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ 'secrets.GITHUB_TOKEN' }}